# Generated by Django 6.0 on 2026-01-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_image_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
